-- Base para comparação de valores de vendas realizadas
-- Utilizando o PEDIDO_FAT_P
SELECT 
    P.PEDF_NR_NF,
    P.PEDF_ID,
    P.PEDF_OPER_ID,
    ROUND(t.pedf_vlr_unit,2) as unitario,
    ROUND(t.pedf_qtde)              AS "QTDE",
    ROUND(SUM(T.PEDF_VLR_TOT),2) AS "S/IMPOSTOS",
    --SOMA COM IMPOSTOS
    ROUND(SUM((T.PEDF_QTDE * T.PEDF_VLR_UNIT)
    +(NVL(T.PEDF_VLR_IPI,0))
    +(NVL(T.PEDF_VLR_SUBS,0))
    -(NVL(T.PEDF_VALOR_DESCONTO,0))
    -(NVL(T.PEDF_VLR_ICMS_DES,0))),2)               AS "C/IMPOSTOS",
    --FIM DA SOMA
    T.PEDF_VLR_IPI,
    T.PEDF_VLR_SUBS,
    T.PEDF_VALOR_DESCONTO,
    P.PEDF_SITUACAO

FROM PEDIDO_FAT_P T, PEDIDO_FAT P
WHERE T.PEDF_PEDF_EMP_ID = P.PEDF_EMP_ID AND T.PEDF_PEDF_ID = P.PEDF_ID
--AND P.PEDF_NR_NF IN (175341)
AND P.PEDF_OPER_ID IN (1,9,21,80,693)    -- OPERAÇÃO DE FATURAMENTO VENDA
AND P.PEDF_NR_NF IS NOT NULL             -- EXIGE NOTA FISCAL
AND P.PEDF_DTA_EMIS BETWEEN '01/07/2023' AND '31/07/2023' --ENTRE DATAS
AND P.PEDF_SITUACAO != 1                 -- NÃO PERMITE CANCELADO
GROUP BY 
    P.PEDF_NR_NF,
    t.pedf_vlr_unit,
    P.PEDF_OPER_ID,
    P.PEDF_ID,
    T.PEDF_VLR_IPI,
    T.PEDF_VLR_SUBS,
    t.pedf_qtde,
    T.PEDF_VALOR_DESCONTO,
    P.PEDF_SITUACAO
ORDER BY 1

-- DEVE SER COMITADO UM DOS DOIS PARA EXECUTAR 
-- UTILIZANDO A TABELA PEDIDO_FAT
select T.PEDF_NR_NF NFE,
       T.PEDF_ID, 
       T.PEDF_VLR_TOT_PED TOTAL,
       T.PEDF_OPER_ID,
       OPF.OPER_DESC
FROM PEDIDO_FAT t, OPERACAO_FAT OPF
WHERE T.PEDF_OPER_ID = OPF.OPER_ID AND T.PEDF_OPER_EMP_ID = OPF.OPER_EMP_ID
AND 
--T.PEDF_NR_NF IN (175341)
T.PEDF_OPER_ID IN (1,9,21,80,693)
AND T.PEDF_NR_NF IS NOT NULL
AND T.PEDF_DTA_EMIS BETWEEN '01/07/2023' AND '31/07/2023'
ORDER BY 1
