SELECT DISTINCT
        C.OPER_EMP_ID,
        C.OPER_ID,
        C.OPER_DESC,
        C.OPER_CVTO_ID,
        CV.CVTO_DESC,
        C.OPER_GEN_ID,
        PG.GEN_DESCRICAO,
        C.OPER_GEN_ID_TB_PRECO_DE,
        C.OPER_GEN_TGEN_ID_TB_PRECO_DE,
        C.OPER_EMITE_NF,
        C.OPER_TP_LIQ,
        C.OPER_DTA_CAD,
        C.OPER_OPERC_EMP_ID

FROM        OPERACAO_COL C 
INNER JOIN  OPERACAO_COL_R CR ON C.OPER_EMP_ID = CR.OPER_OPERC_EMP_ID AND C.OPER_ID = CR.OPER_OPERC_ID
INNER JOIN  COND_VCTO CV      ON C.OPER_CVTO_ID = CV.CVTO_ID AND C.OPER_EMP_ID = CV.CVTO_EMP_ID -- CONDIÇÕES DE VENCIMENTO
INNER JOIN  GENER PG          ON PG.GEN_TGEN_ID = C.OPER_GEN_TGEN_ID AND PG.GEN_EMP_ID = C.OPER_GEN_EMP_ID AND PG.GEN_ID = C.OPER_GEN_ID -- FORMA DE PAGAMENTO
--WHERE C.OPER_EMP_ID = 2
ORDER BY 2,1
