SELECT
     BEM_ID              
    ,BEM_EMP_ID          
    ,BEM_NOME            
    ,BEM_INCREM          
    ,BEM_CONT_ID         
    ,PCTA.GEN_DESCRICAO  
    ,BEM_NR_NF           
    ,BEM_SERIE_NF        
    ,BEM_SITUACAO        
    ,GRUPO.GEN_ID        
    ,GRUPO.GEN_DESCRICAO 
    ,SGRUPO.GEN_ID       
    ,SGRUPO.GEN_DESCRICAO
    ,MOV_DATA
    ,BEM_PLACA_IMOBILIZADO
FROM
   PAT_BEM
  ,GENER PCTA
  ,PAT_CONTAS
  ,GENER SGRUPO
  ,GENER_A SGRUPO_PROP
  ,GENER GRUPO
  ,( SELECT DISTINCT
       MOV_BEM_EMP_ID
      ,MOV_BEM_ID
      ,MOV_BEM_INCREM
      ,MOV_BEM_CONT_EMP_GEN_TGEN_ID
      ,MOV_BEM_CONT_EMP_GEN_EMP_ID
      ,MOV_BEM_CONT_EMP_GEN_ID
      ,MOV_BEM_CONT_ID
      ,MOV_DATA
     FROM PAT_MOVIMENTO
     WHERE
        MOV_EMP_ID     = 2
     AND MOV_TIPO      = 1
   )

WHERE
   PCTA.GEN_TGEN_ID                      = PAT_BEM.BEM_CONT_EMP_GEN_TGEN_ID_PCTA
AND PCTA.GEN_EMP_ID                       = PAT_BEM.BEM_CONT_EMP_GEN_EMP_ID_PCTA
AND PCTA.GEN_ID                           = PAT_BEM.BEM_CONT_EMP_GEN_ID_PCTA
AND PAT_CONTAS.CONT_EMP_GEN_TGEN_ID_PCTA  = PAT_BEM.BEM_CONT_EMP_GEN_TGEN_ID_PCTA
AND PAT_CONTAS.CONT_EMP_GEN_EMP_ID_PCTA   = PAT_BEM.BEM_CONT_EMP_GEN_EMP_ID_PCTA
AND PAT_CONTAS.CONT_EMP_GEN_ID_PCTA       = PAT_BEM.BEM_CONT_EMP_GEN_ID_PCTA
AND PAT_CONTAS.CONT_ID                    = PAT_BEM.BEM_CONT_ID
AND SGRUPO.GEN_TGEN_ID                     = PAT_CONTAS.CONT_GEN_TGEN_ID_SUB_GRUPO
AND SGRUPO.GEN_EMP_ID                      = PAT_CONTAS.CONT_GEN_EMP_ID_SUB_GRUPO
AND SGRUPO.GEN_ID                          = PAT_CONTAS.CONT_GEN_ID_SUB_GRUPO
AND SGRUPO_PROP.GENA_GEN_TGEN_ID           = SGRUPO.GEN_TGEN_ID
AND SGRUPO_PROP.GENA_GEN_EMP_ID            = SGRUPO.GEN_EMP_ID
AND SGRUPO_PROP.GENA_GEN_ID                = SGRUPO.GEN_ID
AND GRUPO.GEN_TGEN_ID                      = SGRUPO_PROP.GENA_GEN_TGEN_ID_PROPRIETARIO_
AND GRUPO.GEN_EMP_ID                       = SGRUPO_PROP.GENA_GEN_EMP_ID_PROPRIETARIO_D
AND GRUPO.GEN_ID                           = SGRUPO_PROP.GENA_GEN_ID_PROPRIETARIO_DE
AND MOV_BEM_EMP_ID                           = BEM_EMP_ID
AND MOV_BEM_ID                               = BEM_ID
AND MOV_BEM_INCREM                           = BEM_INCREM
AND MOV_BEM_CONT_EMP_GEN_TGEN_ID             = BEM_CONT_EMP_GEN_TGEN_ID_PCTA
AND MOV_BEM_CONT_EMP_GEN_EMP_ID              = BEM_CONT_EMP_GEN_EMP_ID_PCTA
AND MOV_BEM_CONT_EMP_GEN_ID                  = BEM_CONT_EMP_GEN_ID_PCTA
AND MOV_BEM_CONT_ID                          = BEM_CONT_ID
AND PAT_BEM.BEM_EMP_ID                     = 2
AND
REPLACE(REPLACE(REPLACE(BEM_ID, '.'), '-'),'/') BETWEEN 
'1951'
AND
'1955'
ORDER BY
BEM_ID



 
