SELECT 'TRANSF_EMI' TIPO,
   PEDFP.PEDF_PROD_ID ID_PRODUTO,
   PROD.PROD_DESC PRODUTO,
   SUM(DECODE(OPER_FAT.OPER_GEN_ID_TP_OPERACAO_DE, 3,
        (NVL(PEDF_QTDE, 0) * (-1)),
        NVL(PEDF_QTDE, 0))) - NVL(P_DEV.QTDE_DEV, 0) QTDE,
   (PEDF.PEDF_NR_NF ||'/'  || PEDF.PEDF_ID ) NOTA_FISCAL,
   PEDF.PEDF_SERIE_NF SERIE,
   TO_CHAR(PEDF.PEDF_LIQU_ID) LIQUIDACAO,
   TRUNC(LIQU.LIQU_DTA_EMIS) EMISSAO,
   TRUNC(LIQU.LIQU_DTA_CAD) DATA_CADASTRO,
   USUARIO.USR_NOME

FROM PEDIDO_FAT PEDF,
   PEDIDO_FAT_P PEDFP,
   PRODUTO_AG PRODAG,
   PRODUTO PROD,
   OPERACAO_FAT OPER_FAT,
   LIQUIDACAO LIQU,
   USUARIO,
   (SELECT PEDFP.PEDF_PROD_EMP_ID EMP_PROD,
       PEDFP.PEDF_PROD_ID PRODUTO,
       SUM(DECODE(OPER_FAT.OPER_GEN_ID_TP_OPERACAO_DE,
            3,
            (NVL(PEDF_QTDE, 0) * (-1)),
            NVL(PEDF_QTDE, 0))) QTDE_DEV

    FROM PEDIDO_FAT   PEDF,
       PEDIDO_FAT_P PEDFP,
       PRODUTO_AG   PRODAG,
       OPERACAO_FAT OPER_FAT,
       LIQUIDACAO   LIQU
   WHERE PEDFP.PEDF_PEDF_EMP_ID = PEDF.PEDF_EMP_ID
     AND PEDFP.PEDF_PEDF_ID = PEDF.PEDF_ID
     AND PRODAG.PRAG_PROD_EMP_ID = PEDFP.PEDF_PROD_EMP_ID
     AND PRODAG.PRAG_PROD_ID = PEDFP.PEDF_PROD_ID
     AND OPER_FAT.OPER_EMP_ID = PEDF.PEDF_OPER_EMP_ID
     AND OPER_FAT.OPER_ID = PEDF.PEDF_OPER_ID
     AND PEDF.PEDF_LIQU_EMP_ID = LIQU.LIQU_EMP_ID
     AND PEDF.PEDF_LIQU_ID = LIQU.LIQU_ID
AND (PEDF_NR_NF Is not Null)
     AND PEDF_EMP_ID = 2
     AND PEDF.PEDF_SITUACAO = 2
     AND TO_CHAR(LIQU.LIQU_DTA_LIB, 'MM/YYYY') = '02/2023' -- Data de pesquisa
     AND OPER_FAT.OPER_GEN_ID_TP_OPERACAO_DE IN (8)
     AND PRODAG.PRAG_GEN_ID IN (4, 5, 10)
     AND PRODAG.PRAG_EMP_ID = 2
   GROUP BY PEDFP.PEDF_PROD_ID, PEDFP.PEDF_PROD_EMP_ID) P_DEV

WHERE PEDFP.PEDF_PEDF_EMP_ID = PEDF.PEDF_EMP_ID
AND PEDFP.PEDF_PEDF_ID = PEDF.PEDF_ID
AND PEDFP.PEDF_PROD_EMP_ID = P_DEV.EMP_PROD(+)
AND PEDFP.PEDF_PROD_ID = P_DEV.PRODUTO(+)
AND PRODAG.PRAG_PROD_EMP_ID = PEDFP.PEDF_PROD_EMP_ID
AND PRODAG.PRAG_PROD_ID = PEDFP.PEDF_PROD_ID
AND PROD.PROD_EMP_ID = PEDFP.PEDF_PROD_EMP_ID
AND PROD.PROD_ID = PEDFP.PEDF_PROD_ID
AND OPER_FAT.OPER_EMP_ID = PEDF.PEDF_OPER_EMP_ID
AND OPER_FAT.OPER_ID = PEDF.PEDF_OPER_ID
AND PEDF.PEDF_LIQU_EMP_ID = LIQU.LIQU_EMP_ID
AND PEDF.PEDF_LIQU_ID = LIQU.LIQU_ID
AND USUARIO.USR_ID = PEDF.PEDF_USR_ID
AND (PEDF_NR_NF Is not Null)
AND PEDF_EMP_ID = 2
AND PEDF.PEDF_SITUACAO IN (0, 2)
AND TO_CHAR(LIQU.LIQU_DTA_EMIS, 'MM/YYYY') = '02/2023' -- Data de pesquisa
AND OPER_FAT.OPER_GEN_ID_TP_OPERACAO_DE IN (8)
AND PRODAG.PRAG_GEN_ID IN (4, 5, 10)
AND PRODAG.PRAG_EMP_ID = 2

GROUP BY PEDF.PEDF_NR_NF,
    PEDF.PEDF_SERIE_NF,
    PEDF.PEDF_ID,
    PEDF.PEDF_LIQU_ID,
    LIQU.LIQU_DTA_EMIS,
    LIQU.LIQU_DTA_CAD,
    USUARIO.USR_NOME,
    PEDFP.PEDF_PROD_ID,
    PEDFP.PEDF_PROD_EMP_ID,
    PROD.PROD_DESC,
    PRAG_QTDE_PRODUZIDA,
    PRAG_TOTAL_CUSTO_FAB,
    P_DEV.QTDE_DEV
UNION

SELECT 'COMPRAS' TIPO,
   ENTR_PROD_ID ID_PRODUTO,
   PROD.PROD_DESC PRODUTO,
   NVL(SUM(DECODE(OPER_QTDE_ENTRADA, '+', ENTR_QTDE, '-', ENTR_QTDE, 'N', 0)), 0) QTDE,
   (ENTRADA_ALM.ENTR_NR_DOC ||'/'  || ENTRADA_ALM.ENTR_ID)        NOTA_FISCAL,
   ENTRADA_ALM.ENTR_SERIE SERIE,
   ' ' LIQUIDACAO,
   TRUNC(ENTRADA_ALM.ENTR_DTA_EMIS) EMISSAO,
   TRUNC(ENTRADA_ALM.ENTR_DTA_CAD) DATA_CADASTRO,
   USUARIO.USR_NOME

FROM ENTRADA_ALM_E,
   ENTRADA_ALM,
   OPERACAO_ALM,
   PRODUTO_AG,
   PRODUTO PROD,
   USUARIO

WHERE ENTR_PROD_ID = PRAG_PROD_ID
AND ENTR_PROD_EMP_ID = PRAG_PROD_EMP_ID
AND PROD.PROD_ID = PRAG_PROD_ID
AND PROD.PROD_EMP_ID = PRAG_PROD_EMP_ID
AND ENTRADA_ALM.ENTR_USR_ID = USUARIO.USR_ID
AND ENTR_ENTR_EMP_ID = ENTR_EMP_ID
AND ENTR_ENTR_ID = ENTRADA_ALM.ENTR_ID
AND ENTR_OPER_ALM_EMP_ID = OPER_EMP_ID
AND ENTR_OPER_ALM_ID = OPER_ID
AND OPER_OPER_RED        = 1
AND ENTR_SITUACAO        = 1
AND (OPER_QTDE_ENTRADA =   '+'
OR   OPER_ESTQ_ATUAL   =   '+'
OR  (OPER_QTDE_ENTRADA =   '-'
OR   OPER_ESTQ_ATUAL   =   '-')
OR (OPER_VLR_ENTR = '+' AND OPER_QTDE_ENTRADA = 'N' AND OPER_ESTQ_ATUAL = 'N'))
AND PRAG_GEN_ID IN (4, 5, 10)
AND ENTR_ENTR_EMP_ID = 2
AND PRAG_EMP_ID = 2
AND PRAG_PROD_EMP_ID = 2
AND TO_CHAR(ENTR_DTA_LANC, 'MM/YYYY') = '02/2023' -- Data pesquisa

GROUP BY ENTR_PROD_ID,
    PROD.PROD_DESC,
    ENTR_DTA_LANC,
    ENTRADA_ALM.ENTR_NR_DOC,
    ENTRADA_ALM.ENTR_DTA_EMIS,
    ENTRADA_ALM.ENTR_DTA_CAD,
    ENTRADA_ALM.ENTR_SERIE,
    ENTRADA_ALM.ENTR_ID,
    USUARIO.USR_NOME
---------------------------------------------------------------------------------------------------------------
UNION -- União das Tabelas

SELECT 'ENTR_DEV' TIPO,
   ENTRDEV.ID_PRODUTO,
   ENTRDEV.PRODUTO,
   SUM(QTDE) QTDE,
   ENTRDEV.NOTA_FISCAL,
   ENTRDEV.SERIE,
   TO_CHAR(ENTRDEV.LIQUIDACAO) LIQUIDACAO,
   TRUNC(ENTRDEV.EMISSAO) EMISSAO,
   TRUNC(ENTRDEV.DATA_CADASTRO) DATA_CADASTRO,
   ENTRDEV.USR_NOME

FROM (SELECT PEDFP.PEDF_PROD_ID ID_PRODUTO,
       PROD.PROD_DESC PRODUTO,
       (PEDF.PEDF_NR_NF ||'/'  || PEDF.PEDF_ID ) NOTA_FISCAL,
       LIQU.LIQU_DTA_EMIS EMISSAO,
       PEDF.PEDF_LIQU_ID LIQUIDACAO,
       PEDF.PEDF_DTA_CAD DATA_CADASTRO,
       PEDF.PEDF_SERIE_NF SERIE,
       USUARIO.USR_NOME,
       SUM(DECODE(OPER_FAT.OPER_GEN_ID_TP_OPERACAO_DE, 3,
            (NVL(PEDF_QTDE, 0) * (-1)),
            NVL(PEDF_QTDE, 0))) QTDE

    FROM PEDIDO_FAT PEDF,
       PEDIDO_FAT_P PEDFP,
       PRODUTO_AG PRODAG,
       PRODUTO PROD,
       PRODUTO_FAT   PF,
       OPERACAO_FAT OPER_FAT,
       LIQUIDACAO LIQU,
       USUARIO

   WHERE PEDFP.PEDF_PEDF_EMP_ID = PEDF.PEDF_EMP_ID
     AND PEDFP.PEDF_PEDF_ID = PEDF.PEDF_ID
     AND PEDF.PEDF_USR_ID = USUARIO.USR_ID
     AND PRODAG.PRAG_PROD_EMP_ID = PEDFP.PEDF_PROD_EMP_ID
     AND PRODAG.PRAG_PROD_ID = PEDFP.PEDF_PROD_ID
     AND PROD.PROD_EMP_ID = PEDFP.PEDF_PROD_EMP_ID
     AND PROD.PROD_ID = PEDFP.PEDF_PROD_ID
     AND PROD.PROD_EMP_ID =  PF.PROF_PROD_EMP_ID
     AND PROD.PROD_ID     =  PF.PROF_PROD_ID
     AND OPER_FAT.OPER_EMP_ID = PEDF.PEDF_OPER_EMP_ID
     AND OPER_FAT.OPER_ID = PEDF.PEDF_OPER_ID
     AND PEDF.PEDF_LIQU_EMP_ID = LIQU.LIQU_EMP_ID
     AND PEDF.PEDF_LIQU_ID = LIQU.LIQU_ID
AND (PEDF_NR_NF Is not Null)
AND PF.PROF_PROD_ID_PROD_CONSOL_DE IS NULL  --- Nao tem Pai..
     AND PEDF_EMP_ID = 2
     AND PEDF.PEDF_SITUACAO = 2
     AND TO_CHAR(LIQU.LIQU_DTA_LIB, 'MM/YYYY') = '02/2023' -- Data de pesquisa
   AND (OPER_FAT.OPER_GEN_ID_TP_OPERACAO_DE = 2
   OR OPER_FAT.OPER_GEN_ID_TP_OPERACAO_DE = 10
   OR
   (OPER_FAT.OPER_GEN_ID_TP_OPERACAO_DE = 1
   AND
   DECODE(OPER_FAT.OPER_TIPO_OPE,NULL,0,OPER_FAT.OPER_TIPO_OPE) NOT IN (1,3,8))
   OR
  (OPER_FAT.OPER_GEN_ID_TP_OPERACAO_DE = 3
  AND
(DECODE(OPER_ESTATISTICA,NULL,'S',OPER_ESTATISTICA)<> 'N'))
  OR
  (OPER_FAT.OPER_GEN_ID_TP_OPERACAO_DE = 4 AND DECODE(OPER_FAT.OPER_TIPO_OPE,NULL,0,OPER_FAT.OPER_TIPO_OPE) IN (2,4,5)))
     AND PRODAG.PRAG_GEN_ID IN (4, 5, 10)
     AND PRODAG.PRAG_EMP_ID = 2

   GROUP BY PEDFP.PEDF_PROD_ID,
        PEDFP.PEDF_PROD_EMP_ID,
        PROD.PROD_DESC,
        PEDF.PEDF_NR_NF,
        PEDF.PEDF_ID ,
        LIQU.LIQU_DTA_EMIS,
        PEDF.PEDF_SERIE_NF,
        PEDF.PEDF_LIQU_ID,
        PEDF.PEDF_DTA_CAD,
        USUARIO.USR_NOME
  UNION

  SELECT PEDFP.PEDF_PROD_ID ID_PRODUTO,
       PROD.PROD_DESC PRODUTO,
       (PEDF.PEDF_NR_NF ||'/'  || PEDF.PEDF_ID ) NOTA_FISCAL,
       LIQU.LIQU_DTA_EMIS EMISSAO,
       PEDF.PEDF_LIQU_ID LIQUIDACAO,
       PEDF.PEDF_DTA_CAD DATA_CADASTRO,
       PEDF.PEDF_SERIE_NF SERIE,
       USUARIO.USR_NOME,
       SUM(NVL(PEDF_QTDE, 0)) QTDE

    FROM PEDIDO_FAT PEDF,
       PEDIDO_FAT_P PEDFP,
       PRODUTO_AG PRODAG,
       PRODUTO PROD,
       PRODUTO_FAT PF,
       OPERACAO_FAT OPER_FAT,
       LIQUIDACAO LIQU,
       USUARIO
   WHERE PEDFP.PEDF_PEDF_EMP_ID = PEDF.PEDF_EMP_ID
     AND PEDFP.PEDF_PEDF_ID = PEDF.PEDF_ID
     AND PRODAG.PRAG_PROD_EMP_ID = PEDFP.PEDF_PROD_EMP_ID
     AND PRODAG.PRAG_PROD_ID = PEDFP.PEDF_PROD_ID
     AND USUARIO.USR_ID = PEDF.PEDF_USR_ID
     AND PROD.PROD_EMP_ID = PEDFP.PEDF_PROD_EMP_ID
     AND PROD.PROD_ID = PEDFP.PEDF_PROD_ID
     AND PROD.PROD_EMP_ID =  PF.PROF_PROD_EMP_ID
     AND PROD.PROD_ID     =  PF.PROF_PROD_ID
     AND OPER_FAT.OPER_EMP_ID = PEDF.PEDF_OPER_EMP_ID
     AND OPER_FAT.OPER_ID = PEDF.PEDF_OPER_ID
     AND PEDF.PEDF_LIQU_EMP_ID = LIQU.LIQU_EMP_ID
     AND PEDF.PEDF_LIQU_ID = LIQU.LIQU_ID
AND (PEDF_NR_NF Is not Null)
     AND PEDF_EMP_ID = 2
     AND PEDF.PEDF_SITUACAO IN (0, 2)
AND PF.PROF_PROD_ID_PROD_CONSOL_DE IS NULL  --- Nao tem Pai..
     AND TO_CHAR(LIQU.LIQU_DTA_EMIS, 'MM/YYYY') = '02/2023' -- Data de pesquisa
AND
(OPER_FAT.OPER_GEN_ID_TP_OPERACAO_DE = 3
AND
(DECODE(OPER_ESTATISTICA,NULL,'S',OPER_ESTATISTICA)<> 'N')
   OR
  (OPER_FAT.OPER_GEN_ID_TP_OPERACAO_DE = 3
  AND
NVL(OPER_PREST_CTAS,'N' )='S')
)
     AND PRODAG.PRAG_GEN_ID IN (4, 5, 10)
     AND PRODAG.PRAG_EMP_ID = 2

GROUP BY PEDFP.PEDF_PROD_ID,
  PEDFP.PEDF_PROD_EMP_ID,
  PROD.PROD_DESC,
  PEDF.PEDF_NR_NF,
  PEDF.PEDF_DTA_CAD,
  PEDF.PEDF_LIQU_ID,
  LIQU.LIQU_DTA_EMIS,
  PEDF.PEDF_SERIE_NF,
  PEDF.PEDF_ID      ,
  USUARIO.USR_NOME
UNION  ALL

SELECT
   ENTR_PROD_ID   ID_PRODUTO,
   PROD.PROD_DESC PRODUTO,
   (ENTRADA_ALM.ENTR_NR_DOC ||'/'  || ENTRADA_ALM.ENTR_ID)        NOTA_FISCAL,
   ENTR_DTA_EMIS EMISSAO,
   0 LIQUIDACAO,
   ENTR_DTA_CAD DATA_CADASTRO,
   ENTR_SERIE SERIE,
   USUARIO.USR_NOME,
   SUM(NVL(ENTR_QTDE,0))   QTDE

FROM
  ENTRADA_ALM_E
   ,ENTRADA_ALM
   ,OPERACAO_ALM
   ,PRODUTO_AG
   ,PRODUTO PROD
   ,USUARIO

WHERE
  ENTR_PROD_ID         = PRAG_PROD_ID
AND ENTR_PROD_EMP_ID     = PRAG_PROD_EMP_ID
AND ENTR_ENTR_EMP_ID     = ENTR_EMP_ID
AND ENTR_ENTR_ID         = ENTRADA_ALM.ENTR_ID
AND ENTR_OPER_ALM_EMP_ID = OPER_EMP_ID
AND ENTR_OPER_ALM_ID     = OPER_ID
AND ENTR_PROD_ID         = PROD_ID
AND ENTR_PROD_EMP_ID     = PROD_EMP_ID
AND ENTRADA_ALM.ENTR_USR_ID   = USR_ID
AND OPER_OPER_RED        = 5  ---Outros
AND OPER_TIPO = 'E'           ---Entrada
AND NVL(OPER_DEVOLUCAO_CLI,'N') = 'S'
AND ENTR_SITUACAO        = 1
AND PRAG_GEN_ID         IN (4, 5, 10)
AND ENTR_ENTR_EMP_ID    = 2
AND PRAG_EMP_ID         = 2
AND PRAG_PROD_EMP_ID    = 2
AND TO_CHAR(ENTR_DTA_LANC,'MM/YYYY') = '02/2023' -- Data de pesquisa

GROUP BY
  ENTR_PROD_ID
   ,ENTR_PROD_EMP_ID
   ,PROD.PROD_DESC
   ,ENTR_NR_DOC
   ,ENTR_DTA_CAD
   ,0
   ,ENTR_DTA_EMIS
   ,ENTR_SERIE
   ,ENTRADA_ALM.ENTR_ID
   ,ENTRADA_ALM.ENTR_NR_DOC
   ,USUARIO.USR_NOME
) ENTRDEV

GROUP BY ENTRDEV.ID_PRODUTO,
    ENTRDEV.PRODUTO,
    ENTRDEV.NOTA_FISCAL,
    ENTRDEV.EMISSAO,
    ENTRDEV.LIQUIDACAO,
    ENTRDEV.DATA_CADASTRO,
    ENTRDEV.SERIE,
    ENTRDEV.USR_NOME
UNION

SELECT 'TRANSF_REC' TIPO
  ,TRANSFREC.ID_PRODUTO
  ,TRANSFREC.PRODUTO
  ,NVL(SUM(TRANSFREC.QTDE_ENT),0) QTDE
  ,TRANSFREC.NOTA_FISCAL
  ,TRANSFREC.SERIE
  ,' ' LIQUIDACAO
  ,TRUNC(TRANSFREC.ENTR_DTA_EMIS) EMISSAO
  ,TRUNC(TRANSFREC.ENTR_DTA_CAD) DATA_CADASTRO
  ,TRANSFREC.USR_NOME

FROM (
SELECT
   ENTR_PROD_ID    ID_PRODUTO
  ,PROD.PROD_DESC  PRODUTO
  ,(ENTRADA_ALM.ENTR_NR_DOC ||'/'  || ENTRADA_ALM.ENTR_ID)        NOTA_FISCAL
  ,ENTRADA_ALM.ENTR_SERIE SERIE
  ,ENTRADA_ALM.ENTR_DTA_EMIS
  ,OPER_QTDE_ENTRADA
  ,OPER_ESTQ_ATUAL
  ,NVL(SUM(ENTR_QTDE),0)   QTDE_ENT
  ,ENTRADA_ALM.ENTR_DTA_CAD
  ,USUARIO.USR_NOME

FROM
   ENTRADA_ALM_E
  ,ENTRADA_ALM
  ,OPERACAO_ALM
  ,PRODUTO_AG
  ,PRODUTO PROD
  ,USUARIO

WHERE
   ENTR_PROD_ID        = PRAG_PROD_ID
AND ENTR_PROD_EMP_ID    = PRAG_PROD_EMP_ID
AND ENTR_ENTR_EMP_ID    = ENTR_EMP_ID
AND ENTR_ENTR_ID        = ENTRADA_ALM.ENTR_ID
AND ENTR_PROD_EMP_ID    = PROD.PROD_EMP_ID
AND ENTR_PROD_ID        = PROD.PROD_ID
AND ENTRADA_ALM.ENTR_USR_ID         = USR_ID
AND ENTR_OPER_ALM_EMP_ID = OPER_EMP_ID
AND ENTR_OPER_ALM_ID     = OPER_ID
AND (OPER_TRANSFERENCIA ='S' OR OPER_OPER_RED  = 4)
AND PRAG_GEN_ID         IN (4, 5, 10)
AND ENTR_ENTR_EMP_ID    = 2
AND PRAG_EMP_ID         = 2
AND PRAG_PROD_EMP_ID    = 2
AND ENTR_SITUACAO       = 1
AND ENTRADA_ALM.ENTR_PEDF_ID IS NULL
AND TO_CHAR(ENTR_DTA_LANC,'MM/YYYY') = '02/2023' -- Data de pesquisa

GROUP BY
   ENTR_PROD_ID
  ,PROD.PROD_DESC
  ,ENTRADA_ALM.ENTR_NR_DOC
  ,ENTRADA_ALM.ENTR_SERIE
  ,ENTRADA_ALM.ENTR_ID
  ,ENTRADA_ALM.ENTR_DTA_EMIS
  ,OPER_QTDE_ENTRADA
  ,OPER_ESTQ_ATUAL
  ,ENTRADA_ALM.ENTR_DTA_CAD
  ,USUARIO.USR_NOME
UNION ALL

SELECT
   ENTR_PROD_ID       ID_PRODUTO
  ,PROD.PROD_DESC     PRODUTO
  ,(ENTRADA_ALM.ENTR_NR_DOC ||'/'  || ENTRADA_ALM.ENTR_ID)        NOTA_FISCAL
  ,ENTRADA_ALM.ENTR_SERIE SERIE
  ,ENTRADA_ALM.ENTR_DTA_EMIS
  ,OPER_QTDE_ENTRADA
  ,OPER_ESTQ_ATUAL
  ,NVL(SUM(ENTR_QTDE),0)   QTDE_ENT
  ,ENTRADA_ALM.ENTR_DTA_CAD
  ,USUARIO.USR_NOME

FROM
   ENTRADA_ALM_E
  ,ENTRADA_ALM
  ,OPERACAO_ALM
  ,PRODUTO_AG
  ,PRODUTO PROD
  ,USUARIO

WHERE
   ENTR_PROD_ID        = PRAG_PROD_ID
AND ENTR_PROD_EMP_ID    = PRAG_PROD_EMP_ID
AND ENTR_PROD_ID        = PROD.PROD_ID
AND ENTR_PROD_EMP_ID    = PROD.PROD_EMP_ID
AND ENTRADA_ALM.ENTR_USR_ID         = USR_ID
AND ENTR_ENTR_EMP_ID    = ENTR_EMP_ID
AND ENTR_ENTR_ID        = ENTRADA_ALM.ENTR_ID
AND ENTR_OPER_ALM_EMP_ID = OPER_EMP_ID
AND ENTR_OPER_ALM_ID     = OPER_ID
AND (OPER_TRANSFERENCIA ='S' OR OPER_OPER_RED = 4)
AND PRAG_GEN_ID         IN (4, 5, 10)
AND ENTR_ENTR_EMP_ID    = 2
AND PRAG_EMP_ID         = 2
AND PRAG_PROD_EMP_ID    = 2
AND ENTR_SITUACAO       = 1
AND ENTRADA_ALM.ENTR_PEDF_ID IS NOT  NULL
AND TO_CHAR(ENTR_DTA_LANC,'MM/YYYY') = '02/2023' -- Data de pesquisa

GROUP BY
   ENTR_PROD_ID
  ,PROD.PROD_DESC
  ,ENTRADA_ALM.ENTR_NR_DOC
  ,ENTRADA_ALM.ENTR_SERIE
  ,ENTRADA_ALM.ENTR_ID
  ,ENTRADA_ALM.ENTR_DTA_EMIS
  ,OPER_QTDE_ENTRADA
  ,OPER_ESTQ_ATUAL
  ,ENTRADA_ALM.ENTR_DTA_CAD
  ,USUARIO.USR_NOME
) TRANSFREC

GROUP BY
TRANSFREC.ID_PRODUTO
,TRANSFREC.PRODUTO
,TRANSFREC.NOTA_FISCAL
,TRANSFREC.SERIE
,TRANSFREC.ENTR_DTA_EMIS
,TRANSFREC.OPER_QTDE_ENTRADA
,TRANSFREC.OPER_ESTQ_ATUAL
,TRANSFREC.USR_NOME
,TRANSFREC.ENTR_DTA_CAD
UNION

SELECT 'CPV' TIPO
   ,PEDFP.PEDF_PROD_ID  ID_PRODUTO
   ,PROD.PROD_DESC      PRODUTO
   ,SUM(NVL(PEDF_QTDE,0)) QTDE
   ,(PEDF.PEDF_NR_NF ||'/'  || PEDF.PEDF_ID ) NOTA_FISCAL
   ,PEDF.PEDF_SERIE_NF    SERIE
   ,TO_CHAR(PEDF.PEDF_LIQU_ID) LIQUIDACAO
   ,TRUNC(LIQU.LIQU_DTA_EMIS)    EMISSAO
   ,TRUNC(LIQU.LIQU_DTA_CAD)     DATA_CADASTRO
   ,USUARIO.USR_NOME

FROM PEDIDO_FAT    PEDF
,PEDIDO_FAT_P  PEDFP
,PRODUTO_AG    PRODAG
,OPERACAO_FAT  OPER_FAT
,LIQUIDACAO    LIQU
,PRODUTO       PROD
,PRODUTO_FAT    PF
,USUARIO

WHERE PEDFP.PEDF_PEDF_EMP_ID = PEDF.PEDF_EMP_ID
AND PEDFP.PEDF_PEDF_ID     = PEDF.PEDF_ID
AND PEDFP.PEDF_PROD_EMP_ID = PROD.PROD_EMP_ID
AND PEDFP.PEDF_PROD_ID     = PROD.PROD_ID
AND PEDFP.PEDF_PROD_EMP_ID =  PF.PROF_PROD_EMP_ID
AND PEDFP.PEDF_PROD_ID     =  PF.PROF_PROD_ID
AND PRODAG.PRAG_PROD_EMP_ID = PEDFP.PEDF_PROD_EMP_ID
AND PRODAG.PRAG_PROD_ID     = PEDFP.PEDF_PROD_ID
AND OPER_FAT.OPER_EMP_ID    = PEDF.PEDF_OPER_EMP_ID
AND OPER_FAT.OPER_ID        = PEDF.PEDF_OPER_ID
AND PEDF.PEDF_LIQU_EMP_ID   = LIQU.LIQU_EMP_ID
AND PEDF.PEDF_LIQU_ID       = LIQU.LIQU_ID
AND PEDF.PEDF_USR_ID        = USUARIO.USR_ID
AND PF.PROF_PROD_ID_PROD_CONSOL_DE IS NULL  --- Nao tem Pai..
AND (PEDF_NR_NF Is not Null)
AND PEDF_EMP_ID = 2
AND PEDF.PEDF_SITUACAO IN (0,2)
AND TO_CHAR(LIQU.LIQU_DTA_EMIS,'MM/YYYY') = '02/2023' -- Data de pesquisa
AND (OPER_FAT.OPER_GEN_ID_TP_OPERACAO_DE = 2
OR
(OPER_FAT.OPER_GEN_ID_TP_OPERACAO_DE = 1
    AND
   DECODE(OPER_FAT.OPER_TIPO_OPE,NULL,0,OPER_FAT.OPER_TIPO_OPE) NOT IN (1,3,8))
   OR
   (OPER_FAT.OPER_GEN_ID_TP_OPERACAO_DE = 4 AND DECODE(OPER_FAT.OPER_TIPO_OPE,NULL,0,OPER_FAT.OPER_TIPO_OPE) IN (2,4,5))
 OR  (OPER_FAT.OPER_GEN_ID_TP_OPERACAO_DE = 10) )
    AND PRODAG.PRAG_GEN_ID IN (4, 5, 10)
    AND PRODAG.PRAG_EMP_ID = 2

GROUP BY PEDFP.PEDF_PROD_ID
   ,PROD.PROD_DESC
   ,PEDF.PEDF_NR_NF
   ,PEDF.PEDF_SERIE_NF
   ,PEDF.PEDF_ID
   ,TO_CHAR(PEDF.PEDF_LIQU_ID)
   ,LIQU.LIQU_DTA_EMIS
   ,LIQU.LIQU_DTA_CAD
   ,USUARIO.USR_NOME
UNION

SELECT 'CPV' TIPO
   ,PROD_FAT.PROF_PROD_ID_PROD_CONSOL_DE  ID_PRODUTO
   ,PROD.PROD_DESC      PRODUTO
   ,ROUND(((SUM(NVL(PEDF_QTDE,0)) ) * CF.PROC_FATOR_CX / C.PROC_FATOR_CX),3)  QTDE
   ,(PEDF.PEDF_NR_NF ||'/'  || PEDF.PEDF_ID ) NOTA_FISCAL
   ,PEDF.PEDF_SERIE_NF    SERIE
   ,TO_CHAR(PEDF.PEDF_LIQU_ID)   LIQUIDACAO
   ,TRUNC(LIQU.LIQU_DTA_EMIS)    EMISSAO
   ,TRUNC(LIQU.LIQU_DTA_CAD)     DATA_CADASTRO
   ,USUARIO.USR_NOME

FROM PEDIDO_FAT    PEDF
,PEDIDO_FAT_P  PEDFP
,PRODUTO_AG    PRODAG
,PRODUTO_FAT   PROD_FAT --
-- DO FILHO
,PRODUTO_C  CF
-- DO PAI
,PRODUTO_C  C
,OPERACAO_FAT  OPER_FAT
,LIQUIDACAO LIQU
,PRODUTO PROD
,USUARIO
    WHERE PEDFP.PEDF_PEDF_EMP_ID = PEDF.PEDF_EMP_ID
    AND PEDFP.PEDF_PEDF_ID     = PEDF.PEDF_ID
    AND PEDFP.PEDF_PROD_EMP_ID = PROD_FAT.PROF_PROD_EMP_ID
    AND PEDFP.PEDF_PROD_ID     = PROD_FAT.PROF_PROD_ID
    AND PROD_FAT.PROF_PROD_EMP_ID = C.PROC_PROD_EMP_ID
    AND PROD_FAT.PROF_PROD_ID_PROD_CONSOL_DE  = C.PROC_PROD_ID ----FATOR CAIXA (PAI)
      -- FATOR CAIXA FILHO
    AND PROD_FAT.PROF_PROD_EMP_ID = CF.PROC_PROD_EMP_ID
    AND PROD_FAT.PROF_PROD_ID     = CF.PROC_PROD_ID --FATOR CAIXA (FILHO)
    AND PRODAG.PRAG_PROD_EMP_ID = PEDFP.PEDF_PROD_EMP_ID
    AND PRODAG.PRAG_PROD_ID     = PROD_FAT.PROF_PROD_ID_PROD_CONSOL_DE
    AND OPER_FAT.OPER_EMP_ID    = PEDF.PEDF_OPER_EMP_ID
    AND OPER_FAT.OPER_ID        = PEDF.PEDF_OPER_ID
    AND PEDF.PEDF_LIQU_EMP_ID   = LIQU.LIQU_EMP_ID
    AND PEDF.PEDF_LIQU_ID       = LIQU.LIQU_ID
    AND PEDF.PEDF_USR_ID        = USUARIO.USR_ID
    AND PROF_PROD_EMP_ID        = PROD.PROD_EMP_ID
    AND PROD_FAT.PROF_PROD_ID_PROD_CONSOL_DE = PROD.PROD_ID
AND (PEDF_NR_NF Is not Null)
    AND PROD_FAT.PROF_PROD_ID_PROD_CONSOL_DE  IS NOT NULL --
    AND PEDF_EMP_ID = 2
    AND PEDF.PEDF_SITUACAO IN (0)
AND TO_CHAR(LIQU.LIQU_DTA_EMIS,'MM/YYYY') = '02/2023' -- Data de pesquisa
AND (OPER_FAT.OPER_GEN_ID_TP_OPERACAO_DE = 2
OR
(OPER_FAT.OPER_GEN_ID_TP_OPERACAO_DE = 1
    AND
   DECODE(OPER_FAT.OPER_TIPO_OPE,NULL,0,OPER_FAT.OPER_TIPO_OPE) NOT IN (1,3,8))
   OR
   (OPER_FAT.OPER_GEN_ID_TP_OPERACAO_DE = 4 AND DECODE(OPER_FAT.OPER_TIPO_OPE,NULL,0,OPER_FAT.OPER_TIPO_OPE) IN (2,4,5))
OR  (OPER_FAT.OPER_GEN_ID_TP_OPERACAO_DE = 10) )
AND PRODAG.PRAG_GEN_ID IN (4, 5, 10)
AND PRODAG.PRAG_EMP_ID = 2

GROUP BY PROD_FAT.PROF_PROD_ID_PROD_CONSOL_DE
   ,PROD.PROD_DESC
   ,PEDF.PEDF_NR_NF
   ,PEDF.PEDF_SERIE_NF
   ,PEDF.PEDF_ID
   ,TO_CHAR(PEDF.PEDF_LIQU_ID)
   ,LIQU.LIQU_DTA_EMIS
   ,LIQU.LIQU_DTA_CAD
   ,USUARIO.USR_NOME
   ,CF.PROC_FATOR_CX
   ,C.PROC_FATOR_CX
UNION

SELECT 'PERDAS'          TIPO
  ,PEDFP.PEDF_PROD_ID  ID_PRODUTO
  ,PROD.PROD_DESC      PRODUTO
  ,SUM(NVL(PEDF_QTDE,0))  QTDE
  ,(PEDF.PEDF_NR_NF ||'/'  || PEDF.PEDF_ID ) NOTA_FISCAL
  ,PEDF.PEDF_SERIE_NF     SERIE
  ,TO_CHAR(PEDF.PEDF_LIQU_ID) LIQUIDACAO
  ,TRUNC(PEDF.PEDF_DTA_EMIS)      EMISSAO
  ,TRUNC(PEDF.PEDF_DTA_CAD)       DATA_CADASTRO
  ,USUARIO.USR_NOME

FROM PEDIDO_FAT    PEDF
,PEDIDO_FAT_P  PEDFP
,PRODUTO_AG    PRODAG
,OPERACAO_FAT  OPER_FAT
,LIQUIDACAO    LIQU
,PRODUTO       PROD
,PRODUTO_FAT   PF
,USUARIO

WHERE PEDFP.PEDF_PEDF_EMP_ID = PEDF.PEDF_EMP_ID
AND PEDFP.PEDF_PEDF_ID     = PEDF.PEDF_ID
AND PEDF.PEDF_USR_ID       = USUARIO.USR_ID
AND PRODAG.PRAG_PROD_EMP_ID = PEDFP.PEDF_PROD_EMP_ID
AND PRODAG.PRAG_PROD_ID     = PEDFP.PEDF_PROD_ID
AND PEDFP.PEDF_PROD_EMP_ID  = PROD.PROD_EMP_ID
AND PEDFP.PEDF_PROD_ID      = PROD.PROD_ID
AND PEDFP.PEDF_PROD_EMP_ID =  PF.PROF_PROD_EMP_ID
AND PEDFP.PEDF_PROD_ID     =  PF.PROF_PROD_ID
AND OPER_FAT.OPER_EMP_ID    = PEDF.PEDF_OPER_EMP_ID
AND OPER_FAT.OPER_ID        = PEDF.PEDF_OPER_ID
AND PEDF.PEDF_LIQU_EMP_ID   = LIQU.LIQU_EMP_ID
AND PEDF.PEDF_LIQU_ID       = LIQU.LIQU_ID
AND (PEDF_NR_NF Is not Null)
AND PEDF_EMP_ID = 2
AND PEDF.PEDF_SITUACAO = 0
AND NVL(OPER_FAT.OPER_PERDAS,'N') = 'S'
AND PF.PROF_PROD_ID_PROD_CONSOL_DE IS NULL  --- Nao tem Pai..
AND TO_CHAR(LIQU.LIQU_DTA_EMIS,'MM/YYYY') = '02/2023' -- Data de pesquisa
AND PRODAG.PRAG_GEN_ID IN (4, 5, 10)
AND PRODAG.PRAG_EMP_ID = 2

GROUP BY PEDFP.PEDF_PROD_ID
  ,PROD.PROD_DESC
  ,PEDF.PEDF_NR_NF
  ,PEDF.PEDF_SERIE_NF
  ,PEDF.PEDF_ID
  ,TO_CHAR(PEDF.PEDF_LIQU_ID)
  ,PEDF.PEDF_DTA_EMIS
  ,PEDF.PEDF_DTA_CAD
  ,USUARIO.USR_NOME
UNION

SELECT 'SAI_DEV'         TIPO
  ,PEDFP.PEDF_PROD_ID  ID_PRODUTO
  ,PROD.PROD_DESC      PRODUTO
  ,SUM(NVL(PEDF_QTDE,0)) QTDE
  ,(PEDF.PEDF_NR_NF ||'/'  || PEDF.PEDF_ID ) NOTA_FISCAL
  ,PEDF.PEDF_SERIE_NF    SERIE
  ,TO_CHAR(PEDF.PEDF_LIQU_ID) LIQUIDACAO
  ,TRUNC(LIQU.LIQU_DTA_EMIS) EMISSAO
  ,TRUNC(LIQU.LIQU_DTA_CAD) DATA_CADASTRO
  ,USUARIO.USR_NOME

FROM PEDIDO_FAT    PEDF
,PEDIDO_FAT_P  PEDFP
,PRODUTO_AG    PRODAG
,OPERACAO_FAT  OPER_FAT
,LIQUIDACAO    LIQU
,PRODUTO       PROD
,USUARIO

WHERE PEDFP.PEDF_PEDF_EMP_ID = PEDF.PEDF_EMP_ID
AND PEDFP.PEDF_PEDF_ID     = PEDF.PEDF_ID
AND PEDFP.PEDF_PROD_EMP_ID = PROD.PROD_EMP_ID
AND PEDFP.PEDF_PROD_ID     = PROD.PROD_ID
AND PEDF.PEDF_USR_ID       = USUARIO.USR_ID
AND PRODAG.PRAG_PROD_EMP_ID = PEDFP.PEDF_PROD_EMP_ID
AND PRODAG.PRAG_PROD_ID     = PEDFP.PEDF_PROD_ID
AND OPER_FAT.OPER_EMP_ID    = PEDF.PEDF_OPER_EMP_ID
AND OPER_FAT.OPER_ID        = PEDF.PEDF_OPER_ID
AND PEDF.PEDF_LIQU_EMP_ID   = LIQU.LIQU_EMP_ID
AND PEDF.PEDF_LIQU_ID       = LIQU.LIQU_ID
AND (PEDF_NR_NF Is not Null)
AND PEDF_EMP_ID = 2
AND PEDF.PEDF_SITUACAO = 0
AND NVL(OPER_FAT.OPER_DEVOLUCAO,'N') = 'S'
AND TO_CHAR(LIQU.LIQU_DTA_EMIS,'MM/YYYY') = '02/2023' -- Data de pesquisa
AND PRODAG.PRAG_GEN_ID IN (4, 5, 10)
AND PRODAG.PRAG_EMP_ID = 2

GROUP BY PEDFP.PEDF_PROD_ID
  ,PROD.PROD_DESC
  ,PEDF.PEDF_NR_NF
  ,PEDF.PEDF_ID
  ,PEDF.PEDF_SERIE_NF
  ,TO_CHAR(PEDF.PEDF_LIQU_ID)
  ,LIQU.LIQU_DTA_EMIS
  ,LIQU.LIQU_DTA_CAD
  ,USUARIO.USR_NOME
UNION

SELECT
'PRODUCAO'         TIPO
,I.INVE_PROD_ID      ID_PRODUTO
,PROD.PROD_DESC      PRODUTO
,MAX(NVL(BKP_PRAG_QTDE_PRODUZIDA,0))  QTDE
, 'S/Nr'NOTA_FISCAL
,' '              SERIE
,' '              LIQUIDACAO
,TRUNC(I.INVE_DATA)        EMISSAO
,TRUNC(I.INVE_DTA_CAD)     DATA_CADASTRO
,USUARIO.USR_NOME

FROM
INVENTARIO I
,PRODUTO_AG_BKP G
,PRODUTO PROD
,USUARIO

WHERE I.INVE_PROD_EMP_ID   = G.BKP_PRAG_PROD_EMP_ID
AND I.INVE_PROD_ID       = G.BKP_PRAG_PROD_ID
AND I.INVE_PROD_EMP_ID   = PROD.PROD_EMP_ID
AND I.INVE_PROD_ID       = PROD.PROD_ID
AND I.INVE_USR_ID        = USUARIO.USR_ID
AND I.INVE_ETPR_EMP_ID   = 2
AND TO_CHAR(INVE_DATA,'MM/YYYY') = '02/2023' -- Data de pesquisa
AND G.BKP_PRAG_GEN_ID IN (4, 5, 10)

GROUP BY
I.INVE_PROD_ID
,PROD.PROD_DESC
,I.INVE_DATA
,I.INVE_DTA_CAD
,USUARIO.USR_NOME
UNION
SELECT
'PRODTERCEIRO'TIPO
,AGB.BKP_PRAG_PROD_ID                                     ID_PRODUTO
,PR.PROD_DESC PRODUTO
,SUM(AGB.BKP_PRAG_QTDE_PRODUZIDA)                         QTDE
,'' NOTA_FISCAL
,''SERIE
,'' LIQUIDACAO
,BKP_PROG_MES_ANO  EMISSAO
,BKP_PRAG_DTA_CAD DATA_CADASTRO
,USUARIO.USR_NOME
FROM PRODUTO_AG_BKP AGB
,GENER     FASE
,PRODUTO   PR
,USUARIO
WHERE  AGB.BKP_PRAG_GEN_TGEN_ID        = FASE.GEN_TGEN_ID
AND    AGB.BKP_PRAG_GEN_EMP_ID         = FASE.GEN_EMP_ID
AND    AGB.BKP_PRAG_GEN_ID             = FASE.GEN_ID
AND    AGB.BKP_PRAG_PROD_EMP_ID        = PR.PROD_EMP_ID
AND    AGB.BKP_PRAG_PROD_ID            = PR.PROD_ID
AND    AGB.BKP_PRAG_USR_ID             = USR_ID
AND    FASE.GEN_ID  IN (
SELECT
ETPR_ID
FROM
ETAPA_PRO
WHERE
ETPR_EMP_ID = 2
AND NVL(ETPR_PROD_TERC,'N') = 'S'
)
AND TO_CHAR(AGB.BKP_PROG_MES_ANO,'MM/YYYY') = '02/2023' -- Data de pesquisa
AND   (AGB.BKP_PRAG_PROD_EMP_ID,
   AGB.BKP_PRAG_PROD_ID) IN   (SELECT PRAG_PROD_EMP_ID                            -- FASE ENVASE
                ,PRAG_PROD_ID
              FROM PRODUTO_AG AG
              WHERE AG.PRAG_EMP_ID = 2
              AND   AG.PRAG_GEN_ID IN (4, 5, 10))
GROUP BY
   AGB.BKP_PRAG_PROD_ID
  ,FASE.GEN_EMP_ID
  ,PR.PROD_DESC
,BKP_PROG_MES_ANO
,BKP_PRAG_DTA_CAD
,USUARIO.USR_NOME
HAVING SUM(AGB.BKP_PRAG_QTDE_PRODUZIDA) > 0
ORDER BY
TIPO
,ID_PRODUTO
;
