SELECT DISTINCT
      T.PAR_GEN_ID_EMBALAGEM    AS EMB_ID, 
      G.GEN_DESCRICAO           AS EMBALAGEM, 
      T.PAR_TIPO_IMPOSTO        AS TIPO_IMP,
      T.PAR_DESCRICAO,
      T.PAR_PERC_DENTRO_UF      AS DENTRO_UF,
      T.PAR_PERC_FORA_UF        AS FORA_UF,
      U.USR_NOME                AS USER_CADASTRO,
      T.PAR_DATA_CAD,
      T.PAR_DATA_VALIDADE
      
FROM MA_PARAM_IMP_MARGEM T
INNER JOIN GENER G ON T.PAR_GEN_EMP_ID_EMBALAGEM = G.GEN_EMP_ID AND T.PAR_GEN_TGEN_ID_EMBALAGEM = G.GEN_TGEN_ID AND T.PAR_GEN_ID_EMBALAGEM = G.GEN_ID
INNER JOIN USUARIO U ON T.PAR_USR_ID_CAD = U.USR_ID
where t.par_emp_id = 2
ORDER BY 1,3
