SELECT
     MATP_PROD_ID
    ,PROD_DESC
    ,MATP_QTDE_CONS
    ,MATP_QTDE_CONS_T
    ,MATP_CUSTO_UNIT
    ,MATP_CUSTO_TOT
    ,MATP_CUSTO_TEO

FROM
     PRODUTO
    ,MATERIA_PRIMA 

WHERE
     MATP_GRCU_GEN_TGEN_ID   = 1219 
AND  MATP_GRCU_EMP_ID =2
AND  MATP_GRCU_GEN_ID        = 4
AND  MATP_GRCU_GEN_EMP_ID    = MATP_GRCU_EMP_ID
AND  PROD_EMP_ID             = MATP_PROD_EMP_ID
AND  PROD_ID                 = MATP_PROD_ID
AND  MATP_QTDE_CONS NOT IN '0'
--AND MATP_DTA_CAD BETWEEN '01/05/2023' AND '31/05/2023'
ORDER BY PROD_DESC

