SELECT
     OPER_ID
    ,OPER_EMP_ID
    ,OPER_DESC
    ,OPER_TIPO
    ,OPER_OPER_RED
    ,OPER_INDUSTRIAL
    ,OPER_CONTAB
    ,NVL(OPER_INVENTARIO,'N') AS OPER_INVENTARIO 
    ,NVL(OPER_DEVOLUCAO,'N') AS OPER_DEVOLUCAO 
    ,OPER_GEN_TGEN_ID_DEPOSITO                   
    ,OPER_GEN_EMP_ID_DEPOSITO                    
    ,OPER_GEN_ID_DEPOSITO                        
FROM
	OPERACAO_ALM
WHERE
	OPER_EMP_ID = 2
  AND OPER_DESC LIKE '%COMPRA%'
AND NVL(OPER_SITUACAO,'H') = 'H'
ORDER BY OPER_DESC
