SELECT   P.PROD_ID ||' - '|| P.PROD_DESC      AS "Produto"            
        ,PC.PROC_LITRAGEM                     AS "Litro"
        ,PC.PROC_FATOR_CX                     AS "Qtde-Emb"
        ,GE.GEN_ID ||' - '|| GE.GEN_DESCRICAO AS "Embalagem"
        ,MC.GEN_ID ||' - '|| MC.GEN_DESCRICAO AS "Marca"
        ,SB.GEN_ID ||' - '|| SB.GEN_DESCRICAO AS "Sabor"
        ,SG.GEN_ID ||' - '|| SG.GEN_DESCRICAO AS "SubGrupo"
        ,CT.GEN_ID ||' - '|| CT.GEN_DESCRICAO AS "Categoria"
        
FROM PRODUTO P 
INNER JOIN PRODUTO_C PC  ON P.PROD_EMP_ID = PC.PROC_PROD_EMP_ID AND P.PROD_ID = PC.PROC_PROD_ID
INNER JOIN GENER GE      ON PC.PROC_GEN_TGEN_ID_EMBALAGEM_DE = GE.GEN_TGEN_ID AND PC.PROC_GEN_ID_EMBALAGEM_DE = GEN_ID AND PC.PROC_GEN_EMP_ID_EMBALAGEM_DE = GE.GEN_EMP_ID
INNER JOIN GENER MC      ON PC.PROC_GEN_TGEN_ID_MARCA_DE = MC.GEN_TGEN_ID AND PC.PROC_GEN_EMP_ID_MARCA_DE = MC.GEN_EMP_ID AND PC.PROC_GEN_ID_MARCA_DE = MC.GEN_ID
INNER JOIN GENER SB      ON PC.PROC_GEN_TGEN_ID_SABOR_DE = SB.GEN_TGEN_ID AND PC.PROC_GEN_EMP_ID_SABOR_DE = SB.GEN_EMP_ID AND PC.PROC_GEN_ID_SABOR_DE = SB.GEN_ID
INNER JOIN GENER SG      ON PC.PROC_GEN_TGEN_ID_CATEGORIA_DE = SG.GEN_TGEN_ID AND PC.PROC_GEN_EMP_ID_CATEGORIA_DE = SG.GEN_EMP_ID AND PC.PROC_GEN_ID_CATEGORIA_DE = SG.GEN_ID
INNER JOIN PRODUTO_TP TP ON P.PROD_ID = TP.PROT_PROD_ID AND P.PROD_EMP_ID = TP.PROT_PROD_EMP_ID
INNER JOIN GENER CT      ON TP.PROT_GEN_TGEN_ID = CT.GEN_TGEN_ID AND TP.PROT_GEN_ID = CT.GEN_ID
WHERE CT.GEN_ID = 3     
AND P.PROD_EMP_ID = 2
AND P.PROD_SITUACAO = 'H'
ORDER BY P.PROD_ID
