--CREATE OR REPLACE VIEW REL_VENDAS_LOGISTICA AS
SELECT DISTINCT
  PF.PEDF_DTA_EMIS                                       AS "EMISSAO",
  PF.PEDF_OPER_ID                                        AS "TP",
  OPF.OPER_DESC                                          AS "OPERACAO FATURAMENTO",
  PF.PEDF_LIQU_ID                                        AS "LIQUIDACAO",
  PF.PEDF_NR_NF                                          AS "NOTA",
  LIQ.LIQU_FRO_ID                                        AS "COD_TRANS",
  LIQ.LIQU_NOME_TRANSP                                   AS "TRANSPORTADORA",
  PF.PEDF_CLI_ID                                         AS "COD_CLIENTE",
  C.CLI_RAZAO_SOCIAL                                     AS "CLIENTE",
  CID.GEN_DESCRICAO                                      AS "CIDADE",
  CID.DESC_PROP_1                                        AS "UF",
  SUM(PFP.PEDF_QTDE)                                     AS "QTDE",
  ROUND(PF.PEDF_VLR_TOT_PED,2)                           AS "TOTAL NOTA",
  PF.PEDF_PESO_BRUTO_TOTAL                               AS "PESO",
  DECODE(LIQ.LIQU_FRETE_C_F,'C','CIF','F','FOB')         AS "TIPO"
FROM PEDIDO_FAT PF
JOIN CLIENTE C                ON PF.PEDF_CLI_ID = C.CLI_ID AND PF.PEDF_CLI_EMP_ID = C.CLI_EMP_ID
JOIN CLIENTE_E CE             ON CE.CLIE_CLI_EMP_ID = C.CLI_EMP_ID AND CE.CLIE_CLI_ID = C.CLI_ID
JOIN GENER$V CID              ON CID.GEN_TGEN_ID = CE.CLIE_GEN_TGEN_ID_CIDADE_DE AND CID.GEN_EMP_ID = CID.GEN_EMP_ID AND CID.GEN_ID = CE.CLIE_GEN_ID_CIDADE_DE
JOIN PEDIDO_FAT_LOGISTICA PFL ON PF.PEDF_LIQU_EMP_ID = PFL.PEDL_LIQU_EMP_ID AND PF.PEDF_LIQU_ID = PFL.PEDL_LIQU_ID
JOIN LIQUIDACAO LIQ           ON PF.PEDF_LIQU_EMP_ID = LIQ.LIQU_EMP_ID AND PF.PEDF_LIQU_ID = LIQ.LIQU_ID
JOIN PEDIDO_FAT_P PFP         ON PFP.PEDF_PEDF_EMP_ID = PF.PEDF_EMP_ID AND PFP.PEDF_PEDF_ID = PF.PEDF_ID
JOIN OPERACAO_FAT OPF         ON PF.PEDF_OPER_EMP_ID = OPF.OPER_EMP_ID AND PF.PEDF_OPER_ID = OPF.OPER_ID
WHERE PF.PEDF_NR_NF IS NOT NULL
--  AND PF.PEDF_NR_NF = 171151  -- Campo de consulta
  AND PF.PEDF_DTA_EMIS >= '01/01/2022'
  AND OPF.OPER_DESC LIKE '%VENDA%'

GROUP BY
  PF.PEDF_DTA_EMIS,
  PF.PEDF_LIQU_ID,
  PF.PEDF_OPER_ID,
  OPF.OPER_DESC,
  PF.PEDF_NR_NF,
  LIQ.LIQU_FRO_ID,
  LIQ.LIQU_NOME_TRANSP,
  LIQ.LIQU_FRETE_C_F,
  PF.PEDF_CLI_ID,
  C.CLI_RAZAO_SOCIAL,
  CID.GEN_DESCRICAO,
  PF.PEDF_VLR_TOT_PED,
  PF.PEDF_PESO_BRUTO_TOTAL,
  CID.DESC_PROP_1
ORDER BY 1,2,3
;
