SELECT  
       T.CLI_ID
       ,T.CLI_RAZAO_SOCIAL
       ,T.CLI_FANTASIA
       ,T.CLI_TELEF1          AS FONE1
       ,T.CLI_TELEF2          AS FONE2
       ,T.CLI_TELEF3          AS FONE3
       ,T.CLI_CGC_CPF         AS CNPJ_CPF
       ,T.CLI_LIMITE_CRED     AS LIMITE_CREDITO
       ,CE.CLIE_ENDERECO      AS ENDERECO
       ,CE.CLIE_COMPLEMENTO   AS COMPLEMENTO
       ,CID.GEN_DESCRICAO     AS CIDADE
       ,CID.GENA_DESCRICAO    AS ESTADO
       ,CE.CLIE_CEP           AS CEP
       ,SIT.GEN_DESCRICAO     AS FORMA_PAGAMENTO
       ,CM.GEN_DESCRICAO      AS TIPO_CLIENTE
       ,CAD.GEN_DESCRICAO     AS CADEIA
       ,P.PEDF_ID             AS PEDIDO
       
FROM  CLIENTE T
     ,CLIENTE_E CE 
     ,GENER$V CID  
     ,GENER SIT 
     ,GENER CM 
     ,GENER CAD
     ,PEDIDO_FAT P
     ,PEDIDO_FAT_C PC

WHERE T.CLI_EMP_ID = CE.CLIE_CLI_EMP_ID AND T.CLI_ID = CE.CLIE_CLI_ID
AND CE.CLIE_GEN_TGEN_ID_CIDADE_DE = CID.GEN_TGEN_ID AND CE.CLIE_GEN_EMP_ID_CIDADE_DE = CID.GEN_EMP_ID AND CE.CLIE_GEN_ID_CIDADE_DE = CID.GEN_ID
AND T.CLI_GEN_TGEN_ID_SITUACAO_DE = SIT.GEN_TGEN_ID AND T.CLI_GEN_EMP_ID_SITUACAO_DE = SIT.GEN_EMP_ID AND T.CLI_GEN_ID_SITUACAO_DE = SIT.GEN_ID
AND T.CLI_GEN_TGEN_ID = CM.GEN_TGEN_ID AND T.CLI_GEN_EMP_ID = CM.GEN_EMP_ID AND T.CLI_GEN_ID = CM.GEN_ID
AND T.CLI_GEN_TGEN_ID_CADEIA_DE = CAD.GEN_TGEN_ID AND T.CLI_GEN_EMP_ID_CADEIA_DE = CAD.GEN_EMP_ID AND T.CLI_GEN_ID_CADEIA_DE = CAD.GEN_ID
AND T.CLI_ID = P.PEDF_CLI_ID AND T.CLI_EMP_ID = P.PEDF_EMP_ID
AND P.PEDF_ID = PC.PEDF_PEDF_ID AND P.PEDF_EMP_ID = PC.PEDF_PEDF_EMP_ID
AND T.CLI_ID = 17845 AND T.CLI_EMP_ID = 2
