select * from (
--------------------------
SELECT CLIENTE,RAZAO_SOCIAL,DOCUMENTO,REFERENCIA,       
TIPO,TO_DATE(DATA_EMIS,'DD/MM/RRRR') EMISSAO,TO_DATE(DATA_ENCE,'DD/MM/RRRR') ENCERTO,       
SUM(DEBITO)+SUM(CREDITO) VALOR,DECODE(SITUACAO,'N','VENDA',
'D','DESC','P','BAIXA','J','JUROS',
'R','DEVOL')||' - '||TRIM(OBSERVACAO) SITUACAO  
FROM (SELECT CLIENTE, RAZAO_SOCIAL,
               DOCUMENTO,DATA_EMIS,DATA_ENCE,               
               REFERENCIA,TIPO,DECODE(TIPO, 'D', SUM(VALOR), 0) DEBITO,
                              DECODE(TIPO, 'C', SUM(VALOR), 0) CREDITO,SUM(VALOR) SALDO,
                              SITUACAO,OBSRV OBSERVACAO 
                              FROM (SELECT EMPRESA,LIQUIDACAO,DATA_EMIS,DATA_ENCE,PEDIDO,NR_NF_REF DOCUMENTO,
                                           CLIENTE,RAZAO_SOCIAL,TIPO_D TIPO,PCTA_REF_D REFERENCIA,HIST_PAD_D,
                                           GRP_DESP_D,DEBITO VALOR,COMP_OBSERVACAO_D OBSRV,SITUACAO
                                           FROM TABLE(BI_DIARIO_AUXILIAR_FIN_CTB$PK.BUSCA_RECEBIMENTO('002,003,004',SYSDATE))                
                                           WHERE EMPRESA <> 0
                              UNION ALL  
                              SELECT EMPRESA,LIQUIDACAO,DATA_EMIS,DATA_ENCE,PEDIDO,NR_NF_REF,CLIENTE,RAZAO_SOCIAL,
                                    TIPO_C,NVL(PCTA_REF_C, PCTA_REF_D),NVL(HIST_PAD_C, HIST_PAD_D),NVL(GRP_DESP_C,
                                    GRP_DESP_D),NVL(CREDITO, 0) CREDITO,COMP_OBSERVACAO_C,SITUACAO
                                       FROM TABLE(BI_DIARIO_AUXILIAR_FIN_CTB$PK.BUSCA_RECEBIMENTO('002,003,004',SYSDATE))                 
                                       WHERE EMPRESA <> 0

         ) WHERE ((TIPO IS NOT NULL OR VALOR <> 0) AND REFERENCIA <> 0)

    AND SITUACAO NOT IN ('J','D')

     AND DOCUMENTO <> 999999
--     AND CLIENTE NOT IN (3183,16893)
     AND DATA_EMIS BETWEEN '03/04/2023' AND '04/04/2023'

 GROUP BY CLIENTE, RAZAO_SOCIAL, TIPO, REFERENCIA, SITUACAO, TIPO, DOCUMENTO, DATA_EMIS, DATA_ENCE, OBSRV) 
       GROUP BY CLIENTE,RAZAO_SOCIAL,DOCUMENTO,REFERENCIA,TIPO,DATA_EMIS,DATA_ENCE,SITUACAO,OBSERVACAO
 HAVING (SUM(DEBITO) <> 0 OR SUM(CREDITO) <> 0) ORDER BY 3 ASC, 6 ASC, 7 ASC, 5 DESC
--------------------------
)M_CLIENTE

UNION ALL

SELECT CLIENTE, RAZAO_SOCIAL, DOCUMENTO, REFERENCIA, 'T' AS TIPO, MIN(EMISSAO) EMISSAO, MAX(ENCERTO) ENCERTO, 
SUM(VALOR),' TOTAL' AS SITUACAO FROM (
-------------------------------------------
SELECT CLIENTE,RAZAO_SOCIAL,DOCUMENTO, 0 AS REFERENCIA,       
TIPO,TO_DATE(DATA_EMIS,'DD/MM/RRRR') EMISSAO,TO_DATE(DATA_ENCE,'DD/MM/RRRR') ENCERTO,       
SUM(DEBITO)+SUM(CREDITO) VALOR,DECODE(SITUACAO,'N','VENDA',
'D','DESC','P','BAIXA','J','JUROS',
'R','DEVOL')||' - '||TRIM(OBSERVACAO) SITUACAO  
FROM (SELECT CLIENTE, RAZAO_SOCIAL,
               DOCUMENTO,DATA_EMIS,DATA_ENCE,               
               REFERENCIA,TIPO,DECODE(TIPO, 'D', SUM(VALOR), 0) DEBITO,
                              DECODE(TIPO, 'C', SUM(VALOR), 0) CREDITO,SUM(VALOR) SALDO,
                              SITUACAO,OBSRV OBSERVACAO 
                              FROM (SELECT EMPRESA,LIQUIDACAO,DATA_EMIS,DATA_ENCE,PEDIDO,NR_NF_REF DOCUMENTO,
                                           CLIENTE,RAZAO_SOCIAL,TIPO_D TIPO,PCTA_REF_D REFERENCIA,HIST_PAD_D,
                                           GRP_DESP_D,DEBITO VALOR,COMP_OBSERVACAO_D OBSRV,SITUACAO
                                           FROM TABLE(BI_DIARIO_AUXILIAR_FIN_CTB$PK.BUSCA_RECEBIMENTO('002,003,004',SYSDATE))                
                                           WHERE EMPRESA <> 0
                              UNION ALL  
                              SELECT EMPRESA,LIQUIDACAO,DATA_EMIS,DATA_ENCE,PEDIDO,NR_NF_REF,CLIENTE,RAZAO_SOCIAL,
                                    TIPO_C,NVL(PCTA_REF_C, PCTA_REF_D),NVL(HIST_PAD_C, HIST_PAD_D),NVL(GRP_DESP_C,
                                    GRP_DESP_D),NVL(CREDITO, 0) CREDITO,COMP_OBSERVACAO_C,SITUACAO
                                       FROM TABLE(BI_DIARIO_AUXILIAR_FIN_CTB$PK.BUSCA_RECEBIMENTO('002,003,004',SYSDATE))                 
                                       WHERE EMPRESA <> 0

         ) WHERE ((TIPO IS NOT NULL OR VALOR <> 0) AND REFERENCIA <> 0)

    AND SITUACAO NOT IN ('J','D')

     AND DOCUMENTO <> 999999
     AND DATA_EMIS BETWEEN '03/04/2023' AND '03/04/2023'
--     AND CLIENTE NOT IN (3183,16893)
 GROUP BY CLIENTE, RAZAO_SOCIAL, TIPO, REFERENCIA, SITUACAO, TIPO, DOCUMENTO, DATA_EMIS, DATA_ENCE, OBSRV) 
       GROUP BY CLIENTE,RAZAO_SOCIAL,DOCUMENTO,REFERENCIA,TIPO,DATA_EMIS,DATA_ENCE,SITUACAO,OBSERVACAO
 HAVING (SUM(DEBITO) <> 0 OR SUM(CREDITO) <> 0) ORDER BY 3 ASC, 6 ASC, 7 ASC, 5 DESC
 -------------------------------
 )M_CLIENTE_TOTAL
        GROUP BY CLIENTE, RAZAO_SOCIAL, DOCUMENTO, REFERENCIA
